/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 2jjB9mR+Qs75qTThQHH+iqpTUxnhWofHrbR+a5T8xjLWkoItKQfbMP3hsq5UtG0ZSDVXj1W0Nr4ovr1VCYRzDw==
 */

/* eslint-disable */
// tslint:disable

interface Wallets {
  /**
   * @default 0
   */
  balance: number
  /**
   * @default current_timestamp()
   */
  createdAt: (string | Date)
  currency: string
  id: number & {readonly __brand?: 'wallets_id'}
  /**
   * @default NULL
   */
  label: (string) | null
  /**
   * @default current_timestamp()
   */
  updatedAt: (string | Date)
  userId: string
}
export default Wallets;

interface Wallets_InsertParameters {
  /**
   * @default 0
   */
  balance?: number
  /**
   * @default current_timestamp()
   */
  createdAt?: (string | Date)
  currency: string
  id: number & {readonly __brand?: 'wallets_id'}
  /**
   * @default NULL
   */
  label?: (string) | null
  /**
   * @default current_timestamp()
   */
  updatedAt?: (string | Date)
  userId: string
}
export type {Wallets_InsertParameters}
