CREATE TABLE IF NOT EXISTS wallets (
    id INT(11) NOT NULL AUTO_INCREMENT,
    userId VARCHAR(255) NOT NULL,
    balance DOUBLE NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (userId)
);
ALTER TABLE wallets AUTO_INCREMENT=1000000;
CREATE INDEX idx_userId ON wallets (userId);