/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: CHyN0Bag/KkH356LiT/2CAcZrF5OPpDkC4eFlfwEv2AzVE6c3G62wyjtlAFzc6gYqq0PUHA/PMIpBMdcjoVwRw==
 */

/* eslint-disable */
// tslint:disable

import Wallets from './wallets'

interface WalletTransactions {
  amount: number
  /**
   * @default current_timestamp()
   */
  createdAt: (string | Date)
  id: number & {readonly __brand?: 'walletTransactions_id'}
  newBalance: number
  previousBalance: number
  /**
   * @default 'pending'
   */
  status: ("pending" | "completed")
  transactionDetails: unknown
  transactionId: string
  transactionType: ("credit" | "debit")
  /**
   * @default current_timestamp()
   */
  updatedAt: (string | Date)
  walletId: Wallets['id']
}
export default WalletTransactions;

interface WalletTransactions_InsertParameters {
  amount: number
  /**
   * @default current_timestamp()
   */
  createdAt?: (string | Date)
  id: number & {readonly __brand?: 'walletTransactions_id'}
  newBalance: number
  previousBalance: number
  /**
   * @default 'pending'
   */
  status?: ("pending" | "completed")
  transactionDetails: unknown
  transactionId: string
  transactionType: ("credit" | "debit")
  /**
   * @default current_timestamp()
   */
  updatedAt?: (string | Date)
  walletId: Wallets['id']
}
export type {WalletTransactions_InsertParameters}
